name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout:
            |
            docs
            includes
            overrides
            mkdocs.yml
      - name: Configure Git Credentials
        run:
          |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: sudo apt-get remove --purge man-db
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('mkdocs.yml', 'requirements.txt') }}-${{ github.sha }}
          path: .cache
          restore-keys:
            |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material[imaging]
      - run: sudo apt-get install pngquant
      - run: mkdocs gh-deploy --force
